import type { Metadata } from "next";
import "./globals.css";
import '../../public/IRANSansWeb/fonts.css';
import { GlobalProvider } from "./GlobalProvider";


export const metadata: Metadata = {
  title: "Decamond",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <GlobalProvider>
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
